#!/usr/bin/env python3
"""Assemble the documentation site out of the files that already exist.

The four READMEs are the documentation: HACS renders `README.md` on Scribe's
page, and tests check that every YAML option appears in all four. So the site
is *built* from them rather than being a second copy that drifts. This script
writes `site-src/` — generated, git ignores it — rewriting the links that only
make sense inside the repository, and `mkdocs.yml` builds from there.

    python3 scripts/build_docs.py && mkdocs serve

Run by `.github/workflows/docs.yaml` before `mkdocs build --strict`.
"""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "site-src"
BLOB = "https://github.com/jonathan-gtd/scribe/blob/master"

# Source file -> page of the site.
PAGES = {
    "README.md": "index.md",
    "README.fr.md": "fr.md",
    "README.es.md": "es.md",
    "README.de.md": "de.md",
    "docs/data-structure.md": "data-structure.md",
    "docs/DEVELOPMENT.md": "DEVELOPMENT.md",
}

# Links that point at the repository layout, and what they become on the site.
LINKS = {
    "](docs/data-structure.md)": "](data-structure.md)",
    "](docs/DEVELOPMENT.md)": "](DEVELOPMENT.md)",
    "](../README.md)": "](index.md)",
    "](README.md)": "](index.md)",
    "](README.fr.md)": "](fr.md)",
    "](README.es.md)": "](es.md)",
    "](README.de.md)": "](de.md)",
    # Files of the repository that are not documentation: on the site they can
    # only be links back to GitHub.
    "](lovelace_scribe_card.yaml)": f"]({BLOB}/lovelace_scribe_card.yaml)",
    "](lovelace_scribe_view.yaml)": f"]({BLOB}/lovelace_scribe_view.yaml)",
}

# A link the site cannot serve: into docs/, to a README, or to a file at the
# root of the repository. Anchors, full URLs and the site's own pages are fine.
LEFTOVER = re.compile(r"\]\((?!https?:|#|mailto:)(?:\./)?(?:docs/|\.\./|README)[^)]*\)")


def page_for(source: Path, page: str) -> str:
    """One source file as a site page."""
    text = source.read_text(encoding="utf-8")
    for old, new in LINKS.items():
        text = text.replace(old, new)

    # The language bar links to every language, including the page itself.
    text = re.sub(rf"\[([^\]]+)\]\({re.escape(page)}\)", r"**\1**", text, count=1)

    # The READMEs carry a table of contents by hand, because GitHub has none.
    # The site builds its own, in the margin; two is one too many.
    text = re.sub(
        r"^## (?:Table of Contents|Table des matières|Índice|Inhaltsverzeichnis)\n.*?(?=^## )",
        "",
        text,
        count=1,
        flags=re.MULTILINE | re.DOTALL,
    )

    return (
        f"<!-- Generated by scripts/build_docs.py from {source.relative_to(ROOT)}; "
        "edit that file, not this one. -->\n\n" + text
    )


def main() -> int:
    missing = [name for name in PAGES if not (ROOT / name).exists()]
    if missing:
        print(f"missing source file(s): {', '.join(missing)}", file=sys.stderr)
        return 1

    shutil.rmtree(BUILD, ignore_errors=True)
    BUILD.mkdir()

    problems = []
    for source, page in PAGES.items():
        text = page_for(ROOT / source, page)
        (BUILD / page).write_text(text, encoding="utf-8")
        problems += [(page, link) for link in LEFTOVER.findall(text)]
        print(f"{source} -> site-src/{page}")

    for page, link in problems:
        print(f"site-src/{page}: link would 404 on the site: {link}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
